# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('sugerencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('latitud', models.CharField(max_length=30)),
                ('longitud', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='farmacia_medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idfarmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appF.farmacia')),
            ],
        ),
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGenerico', models.CharField(max_length=50)),
                ('nombreComercial', models.CharField(max_length=40)),
                ('dosis', models.TextField(max_length=500)),
                ('viaAplicacion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='medicamento_enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idenfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appF.enfermedad')),
                ('idmedicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appF.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='persona_enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('idenfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appF.enfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('apellido', models.CharField(blank=True, max_length=40, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('farmaceutico', 'Farmaceutico')], max_length=30)),
                ('edad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('telefono', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='persona_enfermedad',
            name='idpersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appF.UserProfile'),
        ),
        migrations.AddField(
            model_name='farmacia_medicamento',
            name='idmedicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appF.medicamento'),
        ),
    ]
