# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='sugerencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appF.medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis',
            field=models.CharField(max_length=20),
        ),
    ]
