# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appF', '0002_auto_20160809_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contra',
            field=models.CharField(default='', max_length=40),
        ),
    ]
