# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appF', '0004_farmacia_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='idpersona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appF.UserProfile'),
        ),
    ]
